# MaskRCNN

### Category mapping

In [1]:
from src.utils.category_mappings import load_hm3d_to_maskcat_mapping

mapping = load_hm3d_to_maskcat_mapping()
print(mapping)

                     maskcat
raw_category                
wall                    misc
door                    misc
ceiling                 misc
floor                   misc
picture                 misc
...                      ...
stringer                misc
supporting structure    misc
typewriter              misc
walls                   misc
washbasin top           misc

[1659 rows x 1 columns]


In [2]:
import pandas as pd
import numpy as np

cat_map = pd.read_csv('./../data/raw/train/scene_datasets/hm3d/train/00006-HkseAnWCgqk/HkseAnWCgqk.semantic.txt', sep=',', skiprows=[0], names=['instance','color','hm3d', 'room']).set_index('instance')

print(cat_map)

           color    hm3d  room
instance                      
1         E83FC9   floor     0
2         AC11D9    wall     0
3         F8B27A    wall     0
4         CBF148    wall     0
5         53FC41    wall     0
...          ...     ...   ...
448       6B9D1D    sink    10
449       6E9DB4    wall    10
450       97C568    wall    10
451       727359    wall    10
452       B5EE76  mirror    10

[452 rows x 3 columns]


In [3]:
from scipy.ndimage.morphology import binary_dilation

arr = np.zeros((5,5,5))
arr[2,2,2] = 6
arr = binary_dilation(arr).astype(arr.dtype)
print(arr)

arr = binary_dilation(arr).astype(arr.dtype)
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [1. 1. 1. 1. 1.]
  [0. 1. 1. 1. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
